
## 文件

### 文件的打开和关闭

程序运行的时候，相关数据是保存在内存中的，关闭计算机电源，内存中的数据就丢失了。为了永久的保存数据，必须将数据存储于文件内，文件通常是保存在硬盘、软盘或光盘中。

打开文件就是创造了文件对象。下面的例子中，变量 f 指向一个文件对象。

```python
>>> f = open("test.dat", "w")
>>> print f
<open file 'test.dat', mode 'w' at 0x0151F8A8>
```

函数open的第一个参数是文件名，第二个是打开的模式。"w"表示以写入的方式打开文件。如果文件"test.dat"不存在，open函数就创建它，否则，新创建的文件覆盖已经存在的文件。当我们打印文件对象时，显示了
文件名、模式和对象位置等信息。

为了把一些内容写到文件中，需要调用文件对象的write方法：

```python
>>> f.write("Now is the time")
>>> f.write("to close the file")
>>> f.close()
```

文件的方法close关闭文件。我们向文件test.dat写入了两个字符串，这两个字符串以如下形式存在于文件的同一行：

```sh
Now is the timeto close the file
```

如果要让这两个字符串分别处于一行，则应该在第一个字符串后面加上换行符：

```python
f.write("Now is the time\n")
```

现在可以再一次的打开文件，但这次不是以写的方式，而是以读的方式，即"r"。

```python
f = open("test.dat", "r")
```

如果要以读的方式打开一个不存在的文件，解释器会显示错误信息：

```python
>>> f = open("tes.dat", "r")
IOError: [Errno 2] No such file or directory: 'tes.dat'
```

当创建或读取文件时，Python首先在当前的目录进行工作。若想在别的目录下工作，就必须指明完整的路径。

例如：

```python
>>> f = open("c:\\test.dat", "w")
>>> f.write("OK")
>>> f.close()
```

为了把文件的内容写到字符串中，可以用文件对象的read方法。

```python
text = f.read()
print text
Now is the timeto close the file
```

因为在"time"和"to"之间没有写入空格，所以这两个词连在了一起。

read可以接受数字参数，表示读出一定数量的字符。如果读到文件的末尾，就返回空字符。

```python
>>> f = open("test.dat", "r")
>>> print f.read(5)
Now i
>>> print f.read(100)
s the timeto close the file
>>> print f.read()

>>>
```

接下来的函数是拷贝文件，一次读写五十个字符。第一个参数是源文件名，第二个参数是新文件名。

```python
def copyFile(oldFile, newFile):
  f1 = open(oldFile, "r")
  f2 = open(newFile, "w")
  while 1:
    text = f1.read(50)
    if text == "":
      break
    f2.write(text)
  f1.close()
  f2.close()
  return
```

break表示是当没有字符拷贝，也就是"text"为空字符时，彻底跳出"while"循环，这也是唯一结束"while"循环的方式。

### 文本文件

文本文件包含可打印字符和空格，每一行以换行符为结束标志。Python是处理文本文件的行家里手。下面的例子建立了一个文本文件，它有三行：

```python
>>> f = open("test.dat", "w")
>>> f.write("I love Python!\nHello, world\nGood Bye!\n")
>>> f.close()
```

readline方法每次从文本文件中读取一行的内容，包括换行符：

```python
>>> f = open("test.dat", "r")
>>> print f.readline()
I love Python!

>>>
```

readlines方法以列表的方法返回文件内其余的内容：

```python
>>> print f.readlines()
['Hello, world\n', 'Good Bye!\n']
```

这时已到达文件的末尾，如果在调用上述两个方法，readline 方法返回空字符，readlines方法返回空列表：

```python
>>> print f.readline()

>>> print f.readlines()
[]
```

接下来的例子是行处理程序，函数filterFile拷贝一个文件，同时将旧文件中不是以"＃"开头的行写入新文件中：

```python
def filterFile(old, new):
  sfile = open(old, "r")
  dfile = open(new, "w")
  while 1:
    text = sfile.readline()
    if text == "":
      break
    elif text[0] == "#":
      continue
    else:
      dfile.write(text)
  sfile.close()
  dfile.close()
```

在这个函数里有两个关键字：break和continue。break 表示如果读取的行内容为空，则完全终止 while 的循环；continue 表示若行的首字符为"＃"，则终止这一次的循环，也就是 continue 以下的循环内的语句不执
行了，返回到循环的顶部继续下一次循环。

### 写入变量

write的参数只能是字符串，如果想把其它类型的变量写入文件，就必须将其转换成字符串。一个简单的方法是利用str函数：

```python
>>> f = open("test.dat", "w")
>>> f.write(str(1234.56) + '\n')
>>> f.write(str(1000))
>>> f.close()
```

另一种方法是利用格式化操作符"%"。当操作符"%"的两边是整数时，它是求余数的运算。如果第一个操作符是字符串，它就是格式化操作符。第一个参数是需要格式化的字符串，第二个参数是数组表达式。结果是包含表达式值的字符串。请看下面的例子：

```python
>>> age = 31
>>> "%d" % age
'31'
```

格式化序列"%d"表示数组中的第一个表达式的值应该是整数类型，字母d代表"decimal"。

格式化序列可以出现在字符串的任何位置，所以我们能够在句子中嵌入值：

```python
>>> age = 31
>>> "My age is : %d." % age
'My age is : 31.'
```

格式化序列"%f"对应是浮点数，默认的小数点后面有六位小数。"%s"对应是字符串。表达式要与字符串中的格式化序列相匹配，匹配包含两个方面，一个是有几个表达式，就有几个格式化序列；另一个是格式化序列与表达式值的类型相对应。

```python
>>> "In %d days we make %f million %s." % \
(31, 31*12.59, 'dollars')
'In 31 days we make 390.290000 million dollars.'
>>> "d% d% d%" % (3, 4 ,5 ,6)
ValueError: incomplete format #错误信息
>>> "d%" % 8.0
ValueError: incomplete format #错误信息
```

对于要格式化的数字，我们还能够指定它所占的位数。"%"后面的数字表明数字的位数，如果位数多于数字的实际位数，且该数为正，则在要格式化的数字的前面添加空格；如果该数为负，空格添加在数字的后面：

```python
>>> "%5d" % 1
'     1'
>>> "%-5d" % 1
'1     '
>>> "%4f" % 9.1
'9.100000'
>>> "%3f" % 1234
'1234.000000'
>>> "%3d" % 1234
'1234'
```

对于浮点数，我们还可以指定小数的位数：

```python
>>> "%4.3f" % 1137.98
'1137.980'
```

下面的例子是按照一定的格式打印姓名和工资。姓名是字典的键，工资是字典的值。姓名左对齐，工资右对齐,同时对姓名进行了排序：

```python
>>> def printSalary(salary):
    name = salary.keys()
    name.sort()
    for n in name:
      print "%-12s : %12.2f" % (n,salary[n])
>>> salary = {'pidaqing':1137.9, 'zhangming':737.3, 'pitianjian':5.0}
>>> printSalary(salary)
pidaqing    : 1137.90
pitianjian  : 5.00
zhangming   : 737.30
```

从上述的内容可以看到，为了将不同类型的数据保存到文件，必须将其转换成字符串。结果导致从文件中读的一切内容都是字符串，数据的原始类型信息丢失了。解决的办法是输入pickle模块，用它提供的方法把各种类型的数据存入文件，数据结构的信息也同样被保存了。也就是说，你保存了什么，将来读出的还是什么。例如：

```python
>>> import pickle
>>> f = open("test.dat", "w")
>>> pickle.dump(100, f)
>>> pickle.dump(123.98, f)
>>> pickle.dump((1, 3, "abc"), f)
>>> pickle.dump([4, 5, 7], f)
>>> f.close()
```

在这个例子中，我们用dump方法分别向文件中写入了整数、浮点数、列表和数组。如果你用write方法写入，那是会出错的。

接下来就看能不能把这些数据“原封不动”的读出来：

```python
>>> f = open("test.dat", "r")
>>> a = pickle.load(f)
>>> print a
100
>>> type(a)
<type 'int'>
>>> b = pickle.load(f)
>>> print b
123.98
>>> type(b)
<type 'float'>
>>> c = pickle.load(f)
>>> print c
(1, 3, 'abc')
>>> type(c)
<type 'tuple'>
>>> d = pickle.load(f)
>>> print d
[4, 5, 7]
>>> type(d)
<type 'list'>
```

每调用一次load方法，就得到先前存入的一个变量，而且这个变量还保存着原始类型的信息。

## 异常

## 错误信息

程序出错了，就会产生异常。异常是不可避免的，关键是怎样处理。当然不能任其放任自流，不管不问。起码的要求是解释器终止程序的运行，指出错误类型，以及对错误进行简单描述。

例如，除数为零时，IDE产生一个异常：

```python
>>> print 2/0
ZeroDivisionError: integer division or modulo by zero #异常信息
```

异常信息分为两个部分，冒号前面的是异常类型，之后是对此的简单说明。其它的信息则指出在程序的什么地方出错了。当异常产生时，如果没有代码来处理它，Python对其进行缺省处理，输出一些异常信息并终止程序。

程序在执行的过程中产生异常，但不希望程序终止执行，这时就需要用 try 和 except 语句对异常进行处理。比如，提示用户输入文件名，然后打开文件。若文件不存在，我们也不想程序就此崩溃，处理异常处理就成了关键的部分。

```python
filename = ''
while 1:
  filename = raw_input("Input a file name: ")
  if filename == 'q':
    break
  try:
    f = open(filename, "r")
    print 'Opened a file.'
  except:
    print 'There is no file named', filename
```

try块的语句要求打开一个文件，如果没有异常发生，就忽略except块的内容；如果产生异常，就执行except块内的语句，之后是再一次的循环。

### 自定义异常信息

如果程序检测到错误，我们也可以用raise定义异常。

```python
def inputAge():
  age = input("Input your age:")
  if (age>100 or age<18):
    raise 'BadNumberError', 'out of range'
  return age
```

raise有两个参数，第一个是由我们自己定义的异常类型，第二个是关于此异常的少量说明信息。如果调用inputAge的函数有处理异常的程序，即使inputAge出错，整个程序也能正常运行；否则，程序退出，显示错误信息。

```python
>>> inputAge()
Input your age:31
31
>>> inputAge()
Input your age:109
BadNumberError: out of range #异常信息
```

***一个复杂的例子***

让我们看下面的脚本文件：

```python
while 1:
  try:
    x = int(raw_input("Input a number:"))
    y = int(raw_input("Input a number:"))
    z = x / y
  except ValueError, ev:
    print "That is no valid number.", ev
  except ZeroDivisionError, ez:
    print "divisor is zero:", ez
  except:
    print "Unexpected error."
    raise
  else:
    print "There is no error."
print x , "/" , y , "=" , x/y
```

在这个例子中有三个except语句。一个try语句可以和多个except配合使用，但只可能是其中的一个被执行。

前两个except语句，接受两个参数。第一个参数是异常的类型，第二个参数用于接收异常发生时生成的值，异常是否有这个参数及参数的类型如何，由异常的类型决定。

异常"ValueError"在这里表示：如果你输入的字符串包含非数字类型的字符，这个异常将被引发。

异常"ZeroDivisionError"表示除数为0引发的异常。

最后一个except语句表示当有异常发生，但不是前面定义的两种类型，就执行这条语句。用这样的 except 语句要小心，理由是你很可能把一个应该注意的的程序错误隐藏了。为了防止这种情况的发生，我们用了 raise 语句，将异常抛出。

当没有任何异常发生时，else语句的内容被执行。else语句一定放在所有except语句的后面。
